version: '3'
services:
  db:
    image: mysql:8.0.32
    container_name: cdv-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cdv_app
      MYSQL_USER: cdv-app
      MYSQL_PASSWORD: tajneHaslo123*
  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db



volumes:
  mysql-data: