"""Add mobile version

Revision ID: 25f835cbd3a7
Revises: 5a1c1041affc
Create Date: 2023-01-23 19:03:50.356967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f835cbd3a7'
down_revision = '5a1c1041affc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_version', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile_version')

    # ### end Alembic commands ###
