"""Add new columns

Revision ID: 6188694cefa9
Revises: e731f6cf9a51
Create Date: 2023-01-23 19:05:37.743939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6188694cefa9'
down_revision = 'e731f6cf9a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('mobile_version', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile_version')
        batch_op.drop_column('version')
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
