"""Remove unused fields

Revision ID: b83c736e948f
Revises: 
Create Date: 2023-01-25 17:32:24.085944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b83c736e948f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('mobile_version')
        batch_op.drop_column('lang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('mobile_version', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('version', mysql.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
