"""Remove unused columns

Revision ID: e731f6cf9a51
Revises: 25f835cbd3a7
Create Date: 2023-01-23 19:04:35.332973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e731f6cf9a51'
down_revision = '25f835cbd3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('mobile_version')
        batch_op.drop_column('lang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('mobile_version', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('version', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
